---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
  - us-east-2
  - eu-central-1
keyed_groups:
  # add hosts to tag_Name_value groups for each aws_ec2 host's tags.Name variable
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
